# Generated by Django 5.2.6 on 2025-10-07 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('movement_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default='IN')),
                ('quantity', models.PositiveIntegerField()),
                ('note', models.CharField(max_length=300)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='Product.product')),
            ],
        ),
    ]
