# Generated by Django 5.2.6 on 2025-10-04 18:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default_mlcgud', max_length=255, verbose_name='image'),
        ),
    ]
