# Generated by Django 5.2.6 on 2025-10-19 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='updated_at',
        ),
    ]
