# Generated by Django 5.2.6 on 2025-10-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('out_of_stock', 'out_of_stock'), ('low_stock', 'low_stock'), ('in_stock', 'in_stock')], default='out_of_stock', max_length=30),
        ),
    ]
